import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { StatsCache } from '@/stores/types';
import BarChart from './BarChart';
import ActivityHeatmap from './ActivityHeatmap';

interface UsageStatsProps {
  stats: StatsCache | null;
}

function formatDuration(ms: number): string {
  const hours = Math.floor(ms / 3_600_000);
  const mins = Math.floor((ms % 3_600_000) / 60_000);
  if (hours > 0) return `${hours}h ${mins}m`;
  return `${mins}m`;
}

function formatTokens(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function modelDisplayName(model: string): string {
  if (model.includes('opus')) return 'Opus';
  if (model.includes('sonnet')) return 'Sonnet';
  if (model.includes('haiku')) return 'Haiku';
  return model;
}

const MODEL_COLORS: Record<string, string> = {
  opus: 'bg-purple-500',
  sonnet: 'bg-blue-500',
  haiku: 'bg-emerald-500',
};

function getModelColor(model: string): string {
  for (const [key, color] of Object.entries(MODEL_COLORS)) {
    if (model.includes(key)) return color;
  }
  return 'bg-gray-500';
}

export default function UsageStats({ stats }: UsageStatsProps) {
  if (!stats) {
    return (
      <div className="text-muted-foreground text-sm py-8 text-center">
        No stats data found. Stats are generated by Claude Code.
      </div>
    );
  }

  const chartData = stats.dailyActivity.map((d) => ({
    label: d.date.slice(5), // MM-DD
    value: d.messageCount,
  }));

  const modelEntries = Object.entries(stats.modelUsage);

  return (
    <div className="space-y-6 pt-4">
      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-4 pb-3 px-4">
            <div className="text-2xl font-bold">{stats.totalMessages.toLocaleString()}</div>
            <div className="text-xs text-muted-foreground">Total Messages</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-3 px-4">
            <div className="text-2xl font-bold">{stats.totalSessions}</div>
            <div className="text-xs text-muted-foreground">Total Sessions</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-3 px-4">
            <div className="text-2xl font-bold">{formatDuration(stats.longestSession.duration)}</div>
            <div className="text-xs text-muted-foreground">Longest Session</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-3 px-4">
            <div className="text-2xl font-bold">{stats.lastComputedDate}</div>
            <div className="text-xs text-muted-foreground">Last Updated</div>
          </CardContent>
        </Card>
      </div>

      {/* Daily activity chart */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium">Daily Messages</CardTitle>
        </CardHeader>
        <CardContent>
          <BarChart data={chartData} maxHeight={140} barColor="bg-blue-500" />
          <div className="flex justify-between mt-2 text-[10px] text-muted-foreground">
            {chartData.map((d, i) => (
              <span key={i} className="flex-1 text-center">{d.label}</span>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Model usage breakdown */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Model Usage</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {modelEntries.map(([model, usage]) => {
              const totalTokens = usage.inputTokens + usage.outputTokens + usage.cacheReadInputTokens;
              return (
                <div key={model} className="flex items-center gap-3">
                  <div className={`h-3 w-3 rounded-full shrink-0 ${getModelColor(model)}`} />
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium">{modelDisplayName(model)}</div>
                    <div className="text-xs text-muted-foreground">
                      {formatTokens(totalTokens)} tokens · {formatTokens(usage.inputTokens)} in · {formatTokens(usage.outputTokens)} out
                    </div>
                  </div>
                </div>
              );
            })}
          </CardContent>
        </Card>

        {/* Hour-of-day heatmap */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Activity by Hour</CardTitle>
          </CardHeader>
          <CardContent>
            <ActivityHeatmap hourCounts={stats.hourCounts} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
