import { EventEmitter } from 'node:events';
import { type SessionFileState } from '../parsers/session-state.js';
import type { PlatformAdapter } from '../platform/types.js';
import type { ConductorConfig, DashboardState, DirectiveState, Session, HookEvent } from '../types.js';
import type { FullWorkState, WorkItemFilter, WorkItem } from './work-item-types.js';
export declare class Aggregator extends EventEmitter {
    private state;
    private config;
    private staleTimer;
    private discoveryTimer;
    private paneMapping;
    private discoveredFiles;
    private workState;
    readonly projectFilter: string;
    private adapter;
    constructor(config: ConductorConfig, adapter?: PlatformAdapter);
    getState(): DashboardState;
    getActiveSessions(): Session[];
    initialize(): void;
    refreshTeams(): void;
    refreshTasks(teamName?: string): void;
    refreshAll(): void;
    updateDirectiveState(directiveState: DirectiveState | null, directiveHistory?: DirectiveState[], activeDirectives?: DirectiveState[]): void;
    updateWorkState(workState: FullWorkState): void;
    getWorkState(): FullWorkState;
    getWorkItems(filters?: WorkItemFilter): WorkItem[];
    refreshSessions(): void;
    private rederiveSessionStatuses;
    updateSessionFromFileState(filePath: string, fileState: SessionFileState): void;
    addEvent(event: HookEvent): void;
    refreshProcessDiscovery(): void;
    private applyPaneMappings;
    detectStaleness(): void;
    destroy(): void;
    private buildSessionsFromFileStates;
    private buildSessionActivities;
    private getLatestEventInfo;
    private updateSessionFromEvent;
    private statusFromEventType;
    private getLivePaneIds;
    private emitChange;
}
